// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeoerZGwk_hylCNuRKuASM9QMb7qUt01k',
    appId: '1:481929803319:web:1583c334cd72cceaa5f1b2',
    messagingSenderId: '481929803319',
    projectId: 'epichub-7f226',
    authDomain: 'epichub-7f226.firebaseapp.com',
    storageBucket: 'epichub-7f226.firebasestorage.app',
    measurementId: 'G-VWZE52FWEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN-uiergeWFi66vhzI8UZVTCBWsmuL67Y',
    appId: '1:481929803319:android:f4344d1d63a498a9a5f1b2',
    messagingSenderId: '481929803319',
    projectId: 'epichub-7f226',
    storageBucket: 'epichub-7f226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNg4HsC92ii6D90Ws4Z0kb_rGLU2Fc9xo',
    appId: '1:481929803319:ios:49287a866c1a7c83a5f1b2',
    messagingSenderId: '481929803319',
    projectId: 'epichub-7f226',
    storageBucket: 'epichub-7f226.firebasestorage.app',
    iosClientId: '481929803319-5hh2otain7ijgha233cuqk01lbi0gv2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.epichub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNg4HsC92ii6D90Ws4Z0kb_rGLU2Fc9xo',
    appId: '1:481929803319:ios:49287a866c1a7c83a5f1b2',
    messagingSenderId: '481929803319',
    projectId: 'epichub-7f226',
    storageBucket: 'epichub-7f226.firebasestorage.app',
    iosClientId: '481929803319-5hh2otain7ijgha233cuqk01lbi0gv2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.epichub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeoerZGwk_hylCNuRKuASM9QMb7qUt01k',
    appId: '1:481929803319:web:f73fe093a54022c5a5f1b2',
    messagingSenderId: '481929803319',
    projectId: 'epichub-7f226',
    authDomain: 'epichub-7f226.firebaseapp.com',
    storageBucket: 'epichub-7f226.firebasestorage.app',
    measurementId: 'G-2SZBCSHG2P',
  );
}
